--- #YAML:1.0
name:               ftndb
version:            0.37
abstract:           Application for Fidonet/FTN related processing in an SQL database supported by a Perl DBD module.
author:
    - Robert James Clay <jame@rocasa.us>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    App::Cmd:             0
    Config::Tiny:         0
    DBD::SQLite:          0
    DBI:                  0
    File::Spec:           0
    FTN::Database:        0.34
    FTN::Log:             0.02
    Getopt::Std:          0
    Test::More:           0
    Test::Pod:            1.22
    Test::Pod::Coverage:  1.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
